### ISSUE TITLE
Google OIDC users are blank

### ISSUE THREAD

**Issue by jakejellinek** [tale/headplane#109]
In the users section the usernames are blank when using Google OIDC.

When running tailscale status however, the usernames are shown as first.last@ which comes from the google claims.

Could we show these usernames and perhaps make them not editable (I haven't tested what happens if I try to rename them, I suspect they would lose their link to the OIDC login)

**Comment by tale** [comment]
Sorry for this, I made this fix in a recent commit to use the actual userinfo endpoint instead of reading the claims from auth only. This will land in the next version!

**Comment by tale** [comment]
Should be fixed in `0.5.5`.

**Comment by rarosalion** [comment]
Hmm.. doesn't seem to be fixed? Or at least, not sure get the user account showing the name after the update? I had the same issue, and just updated to 0.5.5 hoping for a fix. I tried re-authenticating one of my devices as well just to check if that might help. The username still shows blank in the headplane UI. This isn't a major issue at the moment, but I'm hoping to migrate my other users to OIDC and it's going to get confusing if they all have blank names!

If it helps, google doesn't actually provide a "username" in the OIDC claim for some reason. Other tools seem to have a fallback if the username is not provided (e.g. the "tailscale status" command seems to be providing the first part of the email "username@"). 

Happy to help debug if required.

**Comment by tale** [comment]
I think I fallback to anonymous. Does the google OIDC flow *always* provide the email, I can change this if necessary.

**Comment by rarosalion** [comment]
From what I can tell, google will provide the email address whenever asked: https://developers.google.com/identity/openid-connect/openid-connect

> Provided only if you included the email scope in your request. The value of this claim may not be unique to this account and could change over time, therefore you should not use this value as the primary identifier to link to your user record. 

I suspect you could setup OIDC without asking for the email scope, but I've never seen any documentation that suggests doing that. If you're just using it as a display name for the user, I think email seems like the best option. Worth keeping the above in mind, though, in case the display name in the UI is tightly linked to the unique user ID.

My config looks like this:
`oidc:
  issuer: "https://accounts.google.com"
  client_id: "{{ headscale_oidc_client_id }}"
  client_secret: "{{ headscale_oidc_client_secret }}"
  scope: ["openid", "profile", "email"]`
`

Thanks for continuing to look into this.

**Comment by tale** [comment]
Just pushed a fix in 9a5952adcbe4a190360c16945e61b7e538415b9d. It should land in the next release that I cut.

**Comment by tale** [comment]
@rarosalion is it fixed in `0.5.7`?
